const $=id=>document.getElementById(id);
const G=$("grid"),GS=$("gridStage"),B=$("board"),M=$("modal"),S=$("sheet"),TM=$("tm"),TS=$("ts");
const TIMES=T.filter(t=>mm(t)<=mm("19:55")),DEFAULT_COLOR="#3e88b4";
let E=load(),edit=null,gesture=null,press=null,tPress=null,fitMode=false,fitScale=1,previousView=null;
function mm(t){const[a,b]=t.split(":").map(Number);return a*60+b}
function ff(v){v=Math.round(v);return String(Math.floor(v/60)).padStart(2,"0")+":"+String(v%60).padStart(2,"0")}
function esc(s){return String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]))}
function clean(s){return String(s||"").replace(/\s*\(profilový predmet\)/gi,"").replace(/\s*\(PP\)/gi,"").trim()}
function load(){try{const x=JSON.parse(localStorage.getItem(K));if(Array.isArray(x)&&x.length)return x.map((e,i)=>({...e,id:e.id||"e"+i,color:e.color||DEFAULT_COLOR,cancelled:!!e.cancelled}))}catch{}return raw.map((e,i)=>({...e,id:"s"+i,color:e.color||DEFAULT_COLOR,cancelled:false}))}
function save(){localStorage.setItem(K,JSON.stringify(E))}
function metrics(){return{day:innerWidth<=700?166:300,time:innerWidth<=700?60:96,ppm:innerWidth<=700?2.2:1.65,head:innerWidth<=700?44:50}}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function snapStart(v){let best=TIMES[0],d=Infinity;for(const t of TIMES){const x=Math.abs(mm(t)-v);if(x<d){d=x;best=t}}return best}
function snapEnd(v,start){const s=mm(start);let best=TIMES[TIMES.length-1],d=Infinity;for(const t of TIMES){const n=mm(t);if(n<=s)continue;const x=Math.abs(n-v);if(x<d){d=x;best=t}}return best}
function eventHeight(e,m){const i=Math.max(0,TIMES.indexOf(e.start)),next=TIMES[Math.min(TIMES.length-1,i+1)],minDur=Math.max(45,mm(next)-mm(e.start));return Math.max(minDur*m.ppm-8,(mm(e.end)-mm(e.start))*m.ppm-8)}
function rect(e,m){return{x:m.time+clamp(+e.day,0,D.length-1)*m.day+4,y:m.head+(mm(e.start)-mm(TIMES[0]))*m.ppm+4,w:m.day-8,h:eventHeight(e,m)}}
function gridHeight(m){return m.head+(mm(TIMES[TIMES.length-1])-mm(TIMES[0]))*m.ppm+2}
function conflicts(){const bad=new Set;for(let i=0;i<E.length;i++)for(let j=i+1;j<E.length;j++){const a=E[i],b=E[j];if(a.day===b.day&&mm(a.start)<mm(b.end)&&mm(a.end)>mm(b.start)){bad.add(a.id);bad.add(b.id)}}return bad}
function applyFit(){const w=+(G.dataset.baseWidth||0),h=+(G.dataset.baseHeight||0);if(!w||!h)return;G.style.width=w+"px";G.style.height=h+"px";G.style.minWidth=w+"px";G.style.minHeight=h+"px";G.style.transformOrigin="0 0";G.style.transform=fitMode?`scale(${fitScale})`:"none";GS.style.width=(fitMode?w*fitScale:w)+"px";GS.style.height=(fitMode?h*fitScale:h)+"px"}
function visibleBoard(){const r=B.getBoundingClientRect(),vv=window.visualViewport;if(!vv)return{w:r.width,h:r.height};const vx=vv.offsetLeft,vy=vv.offsetTop,vr=vx+vv.width,vb=vy+vv.height;return{w:Math.max(1,Math.min(r.right,vr)-Math.max(r.left,vx)),h:Math.max(1,Math.min(r.bottom,vb)-Math.max(r.top,vy))}}
function fitAll(){if(fitMode){fitMode=false;fitScale=1;applyFit();if(previousView){B.scrollLeft=previousView.left;B.scrollTop=previousView.top}previousView=null;return}const w=+(G.dataset.baseWidth||0),h=+(G.dataset.baseHeight||0);if(!w||!h)return;previousView={left:B.scrollLeft,top:B.scrollTop};const v=visibleBoard();fitScale=Math.min(1,Math.max(.1,(v.w-10)/w,(v.h-10)/h));fitScale=Math.min(1,(v.w-10)/w,(v.h-10)/h);if(!Number.isFinite(fitScale)||fitScale<=0)fitScale=1;fitMode=true;applyFit();B.scrollLeft=0;B.scrollTop=0}
function render(){const m=metrics(),h=gridHeight(m),w=m.time+m.day*D.length;G.innerHTML="";G.dataset.baseWidth=w;G.dataset.baseHeight=h;const c=document.createElement("div");c.className="corner";Object.assign(c.style,{width:m.time+"px",height:m.head+"px"});c.textContent="ČAS / DEŇ";G.appendChild(c);TIMES.slice(0,-1).forEach((t,i)=>{const q=document.createElement("div");q.className="time";Object.assign(q.style,{top:m.head+(mm(t)-mm(TIMES[0]))*m.ppm+"px",width:m.time+"px",height:(mm(TIMES[i+1])-mm(t))*m.ppm+"px"});q.textContent=t;G.appendChild(q)});D.forEach((d,di)=>{const q=document.createElement("div");q.className="day";Object.assign(q.style,{left:m.time+di*m.day+"px",width:m.day+"px",height:m.head+"px"});q.textContent=d;G.appendChild(q);for(let i=0;i<TIMES.length-1;i++){const c=document.createElement("div");c.className="cell"+(i%2?" alt":"");c.dataset.day=di;c.dataset.start=TIMES[i];Object.assign(c.style,{left:m.time+di*m.day+"px",top:m.head+(mm(TIMES[i])-mm(TIMES[0]))*m.ppm+"px",width:m.day+"px",height:(mm(TIMES[i+1])-mm(TIMES[i]))*m.ppm+"px"});G.appendChild(c)}});const bad=conflicts();E.forEach(e=>draw(e,bad,m));applyFit()}
function draw(e,bad,m){const r=rect(e,m),el=document.createElement("div");el.className="event mine"+(bad.has(e.id)?" conflict":"")+(e.cancelled?" cancelled":"");el.dataset.id=e.id;Object.assign(el.style,{left:r.x+"px",top:r.y+"px",width:r.w+"px",height:r.h+"px",background:e.color||DEFAULT_COLOR});const n=clean(e.name),details=[e.format,e.room,e.date].filter(Boolean).join(" · ");el.innerHTML=`<div class="content"><div class="name">${esc(n)}</div>${e.teacher?`<div class="teacher">${esc(e.teacher)}</div>`:""}${details?`<div class="info">${esc(details)}</div>`:""}</div>${e.cancelled?'<div class="cancelLabel">×</div>':""}${bad.has(e.id)?'<div class="conflictBadge">KOLÍZIA</div>':""}<div class="handle hy" data-h="y"><i></i></div>`;G.appendChild(el);el.addEventListener("pointerdown",ev=>down(ev,e,el),{passive:false});el.addEventListener("touchstart",ev=>touchStart(ev,e,el),{passive:true});el.addEventListener("touchmove",touchMove,{passive:false});el.addEventListener("touchend",touchEnd,{passive:false});el.addEventListener("touchcancel",cancelTouch,{passive:false})}
function clearPress(){if(press){clearTimeout(press.timer);press=null}}function clearTouchPress(){if(tPress){clearTimeout(tPress.timer);tPress=null}}
function beginMove(e,el,x,y,pointerId){gesture={kind:"move",id:e.id,el,sx:x,sy:y,orig:{day:e.day,start:e.start,end:e.end,left:parseFloat(el.style.left),top:parseFloat(el.style.top)},m:metrics(),live:null,pointerId};el.classList.add("dragging")}
function startDrag(ev,e,el){if(!press||press.pointerId!==ev.pointerId)return;press.active=true;beginMove(e,el,ev.clientX,ev.clientY,ev.pointerId);try{el.setPointerCapture(ev.pointerId)}catch{}}
function startResize(ev,e,el){ev.preventDefault();ev.stopPropagation();clearPress();gesture={kind:"resizeY",id:e.id,el,sx:ev.clientX,sy:ev.clientY,orig:{start:e.start,end:e.end,height:parseFloat(el.style.height)||eventHeight(e,metrics())},m:metrics(),live:null,pointerId:ev.pointerId};el.classList.add("resizing");try{el.setPointerCapture(ev.pointerId)}catch{}}
function down(ev,e,el){if(ev.pointerType==="touch")return;if(ev.button!==undefined&&ev.button!==0)return;const handle=ev.target.closest(".handle");if(handle)return startResize(ev,e,el);clearPress();press={id:e.id,el,pointerId:ev.pointerId,x:ev.clientX,y:ev.clientY,active:false,moved:false};try{el.setPointerCapture(ev.pointerId)}catch{}press.timer=setTimeout(()=>{if(!press||press.pointerId!==ev.pointerId)return;startDrag({pointerId:press.pointerId,clientX:press.x,clientY:press.y},e,el)},420)}
function move(ev){if(ev.pointerType==="touch")return;if(press&&press.pointerId===ev.pointerId&&!press.active){if(Math.hypot(ev.clientX-press.x,ev.clientY-press.y)>18){press.moved=true;clearPress()}return}if(!gesture||gesture.pointerId!==ev.pointerId)return;updateGesture(ev.clientX,ev.clientY,ev)}
function updateGesture(x,y,ev){const e=E.find(z=>z.id===gesture.id);if(!e)return;ev?.preventDefault();ev?.stopPropagation();const m=gesture.m,scale=fitMode?fitScale:1;if(gesture.kind==="move"){const dx=(x-gesture.sx)/scale,dy=(y-gesture.sy)/scale,h=eventHeight(e,m),left=clamp(gesture.orig.left+dx,m.time+4,m.time+4+(D.length-1)*m.day),top=clamp(gesture.orig.top+dy,m.head+4,Math.max(m.head+4,gridHeight(m)-h-4));gesture.live={x:left,y:top};gesture.el.style.left=left+"px";gesture.el.style.top=top+"px"}else{const startMin=mm(gesture.orig.start),next=TIMES[Math.min(TIMES.length-1,Math.max(1,TIMES.indexOf(gesture.orig.start)+1))],minH=Math.max(54,(mm(next)-startMin)*m.ppm-8),bottom=m.head+(startMin-mm(TIMES[0]))*m.ppm+4,maxH=Math.max(minH,gridHeight(m)-bottom-2),height=clamp(gesture.orig.height+(y-gesture.sy)/scale*1.15,minH,maxH);gesture.live={height};gesture.el.style.height=height+"px"}gesture.moved=true}
document.addEventListener("pointermove",move,{passive:false});document.addEventListener("pointerup",finish,{capture:true});document.addEventListener("pointercancel",cancelGesture,{capture:true});
function finish(ev){if(ev.pointerType==="touch")return;if(press&&press.pointerId===ev.pointerId){const p=press,e=E.find(z=>z.id===p.id),active=p.active;clearPress();if(active&&gesture)commitMove(ev);else if(e&&!p.moved)open(e);return}if(gesture&&gesture.pointerId===ev.pointerId&&gesture.kind==="resizeY"){commitResize();gesture=null}}
function commitMove(ev){const g=gesture,e=E.find(x=>x.id===g.id);if(!e)return;g.el.releasePointerCapture?.(ev.pointerId);g.el.classList.remove("dragging");if(g.live){const dx=g.live.x-g.orig.left,dy=g.live.y-g.orig.top;e.day=clamp(g.orig.day+Math.round(dx/g.m.day),0,D.length-1);e.start=snapStart(clamp(mm(g.orig.start)+dy/g.ppm,mm(TIMES[0]),mm(TIMES[TIMES.length-1])-1));const wanted=mm(e.start)+Math.max(1,mm(g.orig.end)-mm(g.orig.start));e.end=TIMES.some(t=>mm(t)===wanted)?ff(wanted):snapEnd(wanted,e.start);if(mm(e.end)>mm(TIMES[TIMES.length-1]))e.end=TIMES[TIMES.length-1];save();render()}gesture=null}
function commitResize(){const g=gesture,e=E.find(z=>z.id===g.id);if(!e)return;g.el.classList.remove("resizing");if(g.live){const endMin=mm(g.orig.start)+(g.live.height+8)/g.m.ppm;e.end=snapEnd(Math.min(endMin,mm(TIMES[TIMES.length-1])),g.orig.start);save();render()}}
function cancelGesture(){clearPress();if(gesture){gesture.el.classList.remove("dragging","resizing");gesture=null}}
function touchStart(ev,e,el){if(ev.touches.length!==1)return;const t=ev.touches[0],handle=ev.target.closest(".handle");clearTouchPress();if(handle){startResize({preventDefault:()=>{},stopPropagation:()=>{},pointerId:t.identifier,clientX:t.clientX,clientY:t.clientY},e,el);ev.stopPropagation();return}tPress={id:e.id,el,pointerId:t.identifier,x:t.clientX,y:t.clientY,active:false,moved:false};tPress.timer=setTimeout(()=>{if(!tPress||tPress.pointerId!==t.identifier)return;tPress.active=true;beginMove(e,el,t.clientX,t.clientY,t.identifier)},420)}
function touchMove(ev){if(ev.touches.length>1){cancelTouch();return}const t=ev.touches[0];if(!t)return;if(tPress&&tPress.pointerId===t.identifier&&!tPress.active){if(Math.hypot(t.clientX-tPress.x,t.clientY-tPress.y)>18){tPress.moved=true;clearTouchPress()}return}if(!gesture||gesture.pointerId!==t.identifier)return;updateGesture(t.clientX,t.clientY,ev)}
function touchEnd(ev){const id=ev.changedTouches[0]?.identifier;if(!id&&id!==0)return;if(gesture&&gesture.pointerId===id&&gesture.kind==="resizeY"){commitResize();gesture=null;clearTouchPress();return}if(tPress&&tPress.pointerId===id){const p=tPress,e=E.find(z=>z.id===p.id),active=p.active;clearTouchPress();if(active&&gesture){commitTouchMove();gesture=null}else if(e&&!p.moved)open(e)}}
function commitTouchMove(){const g=gesture,e=E.find(z=>z.id===g.id);if(!e)return;g.el.classList.remove("dragging");if(g.live){const dx=g.live.x-g.orig.left,dy=g.live.y-g.orig.top;e.day=clamp(g.orig.day+Math.round(dx/g.m.day),0,D.length-1);e.start=snapStart(clamp(mm(g.orig.start)+dy/g.ppm,mm(TIMES[0]),mm(TIMES[TIMES.length-1])-1));const wanted=mm(e.start)+Math.max(1,mm(g.orig.end)-mm(g.orig.start));e.end=TIMES.some(t=>mm(t)===wanted)?ff(wanted):snapEnd(wanted,e.start);if(mm(e.end)>mm(TIMES[TIMES.length-1]))e.end=TIMES[TIMES.length-1];save();render()}}
function cancelTouch(){clearTouchPress();if(gesture&&gesture.kind==="move"){gesture.el.classList.remove("dragging");gesture=null}}
function fill(){$("start").innerHTML=TIMES.slice(0,-1).map(t=>`<option>${t}</option>`).join("");$("end").innerHTML=TIMES.slice(1).map(t=>`<option>${t}</option>`).join("")}
function showModal(){S.style.transform="translateY(0)";M.classList.add("open")}
function open(e){edit=e.id;$("badge").textContent="UPRAVIŤ HODINU";$("mt").textContent="Upraviť hodinu";$("name").value=e.name||"";$("day").value=e.day;$("start").value=e.start;$("end").value=e.end;$("format").value=e.format||"";$("room").value=e.room||"";$("teacher").value=e.teacher||"";$("date").value=e.date||"";$("note").value=e.note||"";$("color").value=e.color||DEFAULT_COLOR;$("cancelled").checked=!!e.cancelled;$("copy").style.display="block";$("del").style.display="block";showModal()}
function add(day=0,start="08:00"){edit=null;$("badge").textContent="NOVÁ HODINA";$("mt").textContent="Pridať hodinu";["name","format","room","teacher","date","note"].forEach(id=>$(id).value="");$("day").value=day;$("start").value=start;const idx=Math.max(0,TIMES.indexOf(start));$("end").value=TIMES[Math.min(TIMES.length-1,idx+1)];$("color").value=DEFAULT_COLOR;$("cancelled").checked=false;$("copy").style.display="none";$("del").style.display="none";showModal();setTimeout(()=>$('name').focus(),80)}
function addAt(day,start){add(day,start)}
function close(){M.classList.remove("open");S.style.transform="translateY(0)"}
G.addEventListener("click",ev=>{const c=ev.target.closest(".cell");if(c)addAt(+c.dataset.day,c.dataset.start)});
$("add").onclick=()=>add();$("cancel").onclick=close;
$("save").onclick=()=>{const d={day:+$("day").value,start:$("start").value,end:$("end").value,name:$("name").value.trim()||"Nová hodina",type:"mine",format:$("format").value.trim(),room:$("room").value.trim(),teacher:$("teacher").value.trim(),date:$("date").value.trim(),note:$("note").value.trim(),color:$("color").value||DEFAULT_COLOR,cancelled:$("cancelled").checked};if(mm(d.end)<=mm(d.start))return;if(edit){const i=E.findIndex(x=>x.id===edit);if(i>=0)E[i]={...E[i],...d}}else E.push({...d,id:crypto.randomUUID?.()||String(Date.now())});save();close();render()};
$("copy").onclick=()=>{const e=E.find(x=>x.id===edit);if(e){E.push({...e,id:crypto.randomUUID?.()||String(Date.now())});save();close();render()}};
$("del").onclick=()=>{E=E.filter(x=>x.id!==edit);save();close();render()};
function sheetDrag(hit,target,fn){let y=null;hit.onpointerdown=e=>{e.preventDefault();y=e.clientY;try{hit.setPointerCapture(e.pointerId)}catch{}target.classList.add("drag")};hit.onpointermove=e=>{if(y===null)return;e.preventDefault();target.style.transform=`translateY(${clamp(e.clientY-y,0,360)}px)`};hit.onpointerup=e=>{if(y===null)return;const d=e.clientY-y;y=null;target.classList.remove("drag");if(d>55){target.style.transform="translateY(110%)";setTimeout(fn,180)}else target.style.transform="translateY(0)"}}
sheetDrag($("grab"),S,close);sheetDrag($("tgrab"),TS,()=>TM.classList.remove("open"));
$("title").onclick=()=>{$("titleInput").value=localStorage.getItem(TK)||"POLM · ZS 2026/27";TM.classList.add("open")};$("tcancel").onclick=()=>TM.classList.remove("open");$("tsave").onclick=()=>{localStorage.setItem(TK,$("titleInput").value.trim()||"POLM · ZS 2026/27");TM.classList.remove("open");render()};
$("zoomFit").onclick=fitAll;
function recomputeFit(){if(!fitMode)return;const w=+(G.dataset.baseWidth||0),h=+(G.dataset.baseHeight||0);if(!w||!h)return;const v=visibleBoard();fitScale=Math.min(1,(v.w-10)/w,(v.h-10)/h);if(!Number.isFinite(fitScale)||fitScale<=0)fitScale=1;applyFit();B.scrollLeft=0;B.scrollTop=0}
window.addEventListener("resize",()=>requestAnimationFrame(()=>{render();recomputeFit()}));
if(window.visualViewport)window.visualViewport.addEventListener("resize",()=>requestAnimationFrame(recomputeFit));
fill();render();
