document.body.innerHTML=`<div class="app"><header class="top"><div class="brand"><i class="dot"></i><div class="title" id="title">POLM · ZS 2026/27</div></div><button class="add" id="add" aria-label="Pridať">＋</button></header><main class="board" id="board"><div class="grid" id="grid"></div></main></div><div class="modal" id="modal"><section class="sheet" id="sheet"><div class="grabhit" id="grab"><i class="grab"></i></div><div class="badge" id="badge">NOVÁ HODINA</div><h2 id="mt">Pridať hodinu</h2><div class="form"><div class="field full"><label>Predmet</label><input id="name" autocomplete="off"></div><div class="field"><label>Deň</label><select id="day"><option value="0">Pondelok</option><option value="1">Utorok</option><option value="2">Streda</option><option value="3">Štvrtok</option><option value="4">Piatok</option></select></div><div class="field"><label>Začiatok</label><select id="start"></select></div><div class="field"><label>Koniec</label><select id="end"></select></div><div class="field"><label>P/S</label><input id="format"></div><div class="field"><label>Miestnosť</label><input id="room"></div><div class="field full"><label>Vyučujúci</label><input id="teacher"></div><div class="field"><label>Dátumy</label><input id="date"></div><div class="field"><label>Farba</label><input id="color" type="color" value="#3e88b4" class="colorInput"></div><div class="field full"><label>Moja poznámka</label><textarea id="note"></textarea></div><div class="field full"><label>Osobné označenie</label><label class="check"><input type="checkbox" id="cancelled"> Túto hodinu tento týždeň nemám</label></div></div><div class="actions"><button class="cancel" id="cancel">Zrušiť</button><button class="copy" id="copy">Kopírovať</button><button class="delete" id="del">Vymazať</button><button class="save" id="save">Uložiť</button></div></section></div><div class="modal titleModal" id="tm"><section class="sheet" id="ts"><div class="grabhit" id="tgrab"><i class="grab"></i></div><div class="badge">NASTAVENIE</div><h2>Názov rozvrhu</h2><div class="form"><div class="field full"><label>Názov</label><input id="titleInput" autocomplete="off"></div></div><div class="actions"><button class="cancel" id="tcancel">Zrušiť</button><button class="save" id="tsave">Uložiť</button></div></section></div>`;
const $=id=>document.getElementById(id),G=$("grid"),B=$("board"),M=$("modal"),S=$("sheet"),TM=$("tm"),TS=$("ts");
const TIMES=T.filter(x=>mm(x)<=mm("19:55")),DEFAULT_COLOR="#3e88b4";
let E=load(),edit=null,gesture=null,lastTap={id:null,time:0};
function mm(t){let[a,b]=t.split(":").map(Number);return a*60+b}function ff(v){v=Math.round(v);return String(Math.floor(v/60)).padStart(2,"0")+":"+String(v%60).padStart(2,"0")}
function esc(s){return String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]))}
function clean(s){return String(s||"").replace(/\s*\(profilový predmet\)/gi,"").replace(/\s*\(PP\)/gi,"").trim()}
function load(){try{let x=JSON.parse(localStorage.getItem(K));if(Array.isArray(x)&&x.length)return x.map((e,i)=>({...e,id:e.id||"e"+i,cancelled:!!e.cancelled,color:e.color||DEFAULT_COLOR}))}catch{}return raw.map((e,i)=>({...e,id:"s"+i,cancelled:false,color:e.color||DEFAULT_COLOR}))}
function save(){localStorage.setItem(K,JSON.stringify(E))}
function metrics(){const mobile=innerWidth<=700;return{day:mobile?166:300,time:mobile?60:96,ppm:mobile?2.2:1.65,head:mobile?44:50}}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function snapStart(v){let best=TIMES[0],dist=1e9;for(const t of TIMES){const d=Math.abs(mm(t)-v);if(d<dist){dist=d;best=t}}return best}
function snapEnd(v,start){const s=mm(start);let best=TIMES[TIMES.length-1],dist=1e9;for(const t of TIMES){const n=mm(t);if(n<=s)continue;const d=Math.abs(n-v);if(d<dist){dist=d;best=t}}return best}
function eventHeight(e,m){const si=Math.max(0,TIMES.findIndex(t=>t===e.start)),next=TIMES[Math.min(TIMES.length-1,si+1)],minDur=Math.max(45,mm(next)-mm(e.start));return Math.max(minDur*m.ppm-8,(mm(e.end)-mm(e.start))*m.ppm-8)}
function rect(e,m){return{x:m.time+clamp(+e.day,0,D.length-1)*m.day+4,y:m.head+(mm(e.start)-mm(TIMES[0]))*m.ppm+4,w:m.day-8,h:eventHeight(e,m)}}
function gridHeight(m){return m.head+(mm(TIMES[TIMES.length-1])-mm(TIMES[0]))*m.ppm+2}
function conflicts(){const bad=new Set;for(let i=0;i<E.length;i++)for(let j=i+1;j<E.length;j++){const a=E[i],b=E[j];if(a.day===b.day&&mm(a.start)<mm(b.end)&&mm(a.end)>mm(b.start)){bad.add(a.id);bad.add(b.id)}}return bad}
function render(){const m=metrics(),totalH=gridHeight(m),totalW=m.time+m.day*D.length;G.innerHTML="";G.style.width=totalW+"px";G.style.minWidth=totalW+"px";G.style.height=totalH+"px";G.style.minHeight=totalH+"px";const corner=document.createElement("div");corner.className="corner";corner.style.width=m.time+"px";corner.style.height=m.head+"px";corner.textContent="ČAS / DEŇ";G.appendChild(corner);TIMES.slice(0,-1).forEach((t,i)=>{const q=document.createElement("div");q.className="time";q.style.top=m.head+(mm(t)-mm(TIMES[0]))*m.ppm+"px";q.style.width=m.time+"px";q.style.height=(mm(TIMES[i+1])-mm(t))*m.ppm+"px";q.textContent=t;G.appendChild(q)});D.forEach((d,di)=>{const q=document.createElement("div");q.className="day";q.style.left=m.time+di*m.day+"px";q.style.width=m.day+"px";q.style.height=m.head+"px";q.textContent=d;G.appendChild(q);for(let i=0;i<TIMES.length-1;i++){const c=document.createElement("div");c.className="cell"+(i%2?" alt":"");c.style.left=m.time+di*m.day+"px";c.style.top=m.head+(mm(TIMES[i])-mm(TIMES[0]))*m.ppm+"px";c.style.width=m.day+"px";c.style.height=(mm(TIMES[i+1])-mm(TIMES[i]))*m.ppm+"px";G.appendChild(c)}});const bad=conflicts();E.forEach(e=>draw(e,bad,m))}
function fitText(el){const box=el.querySelector(".content"),name=el.querySelector(".name"),teacher=el.querySelector(".teacher"),info=el.querySelector(".info");if(!box||!name)return;let ns=parseFloat(getComputedStyle(name).fontSize),ts=teacher?parseFloat(getComputedStyle(teacher).fontSize):0,is=info?parseFloat(getComputedStyle(info).fontSize):0;for(let i=0;i<24&&box.scrollHeight>box.clientHeight+1;i++){if(name&&ns>8){ns-=.35;name.style.fontSize=ns+"px"}if(teacher&&ts>6.8){ts-=.2;teacher.style.fontSize=ts+"px"}if(info&&is>5.5){is-=.15;info.style.fontSize=is+"px"}}}
function draw(e,bad,m){const r=rect(e,m),el=document.createElement("div");el.className="event mine"+(bad.has(e.id)?" conflict":"")+(e.cancelled?" cancelled":"");el.dataset.id=e.id;el.style.left=r.x+"px";el.style.top=r.y+"px";el.style.width=r.w+"px";el.style.height=r.h+"px";el.style.background=e.color||DEFAULT_COLOR;el.style.setProperty("--tile",e.color||DEFAULT_COLOR);const n=clean(e.name),long=n.length>45,compact=r.h<130;el.classList.toggle("compact",compact);const details=[e.format,e.room,e.date].filter(Boolean).join(" · ");el.innerHTML=`<div class="content"><div class="name ${long?"long":""}">${esc(n)}</div>${e.teacher?`<div class="teacher">${esc(e.teacher)}</div>`:""}${details?`<div class="info">${esc(details)}</div>`:""}</div>${e.cancelled?'<div class="cancelLabel">×</div>':""}${bad.has(e.id)?'<div class="conflictBadge">KOLÍZIA</div>':""}<div class="moveZone"></div><div class="handle hy" data-h="y"><i></i></div>`;G.appendChild(el);requestAnimationFrame(()=>fitText(el));el.onpointerdown=ev=>down(ev,e,el);el.onpointerup=ev=>up(ev,e,el)}
function down(ev,e,el){if(ev.button!==undefined&&ev.button!==0)return;const h=ev.target.closest?.(".handle")?.dataset.h;if(h){ev.preventDefault();ev.stopPropagation();gesture={kind:"resizeY",id:e.id,el,sx:ev.clientX,sy:ev.clientY,orig:{start:e.start,end:e.end,height:parseFloat(el.style.height)||eventHeight(e,metrics())},moved:false};el.classList.add("resizing");try{el.setPointerCapture(ev.pointerId)}catch{};return}gesture={kind:"move",id:e.id,el,sx:ev.clientX,sy:ev.clientY,orig:{day:e.day,start:e.start,end:e.end,left:parseFloat(el.style.left)||0,top:parseFloat(el.style.top)||0},moved:false};el.classList.add("dragging");try{el.setPointerCapture(ev.pointerId)}catch{}}
function move(ev){if(!gesture)return;const e=E.find(x=>x.id===gesture.id);if(!e)return;const dx=ev.clientX-gesture.sx,dy=ev.clientY-gesture.sy;if(Math.hypot(dx,dy)<2)return;ev.preventDefault();const m=metrics();if(gesture.kind==="move"){const h=gesture.orig.height||eventHeight(e,m),maxX=m.time+4+(D.length-1)*m.day,maxY=Math.max(m.head+4,gridHeight(m)-h-4),left=clamp(gesture.orig.left+dx,m.time+4,maxX),top=clamp(gesture.orig.top+dy,m.head+4,maxY);gesture.el.style.left=left+"px";gesture.el.style.top=top+"px";gesture.live={x:left,y:top}}else{const startMin=mm(gesture.orig.start),next=TIMES[Math.min(TIMES.length-1,Math.max(1,TIMES.indexOf(gesture.orig.start)+1))],minH=Math.max(54,(mm(next)-startMin)*m.ppm-8),bottomStart=m.head+(startMin-mm(TIMES[0]))*m.ppm+4,maxH=Math.max(minH,gridHeight(m)-bottomStart-2);gesture.live={height:clamp(gesture.orig.height+dy,minH,maxH)};gesture.el.style.height=gesture.live.height+"px"}gesture.moved=true}
document.addEventListener("pointermove",move,{passive:false});
document.addEventListener("pointerup",()=>{if(!gesture)return;const g=gesture,e=E.find(x=>x.id===g.id);g.el.classList.remove("dragging","resizing");if(e&&g.moved){const m=metrics();if(g.kind==="move"){const dx=g.live.x-g.orig.left,dy=g.live.y-g.orig.top,dayDelta=Math.round(dx/m.day),rawStart=mm(g.orig.start)+dy/m.ppm;e.day=clamp(g.orig.day+dayDelta,0,D.length-1);e.start=snapStart(clamp(rawStart,mm(TIMES[0]),mm(TIMES[TIMES.length-1])-1));const dur=Math.max(1,mm(g.orig.end)-mm(g.orig.start)),wanted=mm(e.start)+dur;e.end=TIMES.some(t=>mm(t)===wanted)?ff(wanted):snapEnd(wanted,e.start);if(mm(e.end)>mm(TIMES[TIMES.length-1]))e.end=TIMES[TIMES.length-1]}else{const endMin=mm(g.orig.start)+(g.live.height+8)/m.ppm;e.end=snapEnd(Math.min(endMin,mm(TIMES[TIMES.length-1])),g.orig.start)}save();render()}gesture=null});
function up(ev,e,el){if(!gesture||gesture.id!==e.id||gesture.kind!=="move"||gesture.moved)return;const now=Date.now();if(lastTap.id===e.id&&now-lastTap.time<430){lastTap={id:null,time:0};open(e)}else lastTap={id:e.id,time:now}}
function fill(){$("start").innerHTML=TIMES.slice(0,-1).map(t=>`<option>${t}</option>`).join("");$("end").innerHTML=TIMES.slice(1).map(t=>`<option>${t}</option>`).join("")}
function open(e){edit=e.id;$("badge").textContent="UPRAVIŤ HODINU";$("mt").textContent="Upraviť hodinu";$("name").value=e.name||"";$("day").value=e.day;$("start").value=e.start;$("end").value=e.end;$("format").value=e.format||"";$("room").value=e.room||"";$("teacher").value=e.teacher||"";$("date").value=e.date||"";$("note").value=e.note||"";$("color").value=e.color||DEFAULT_COLOR;$("cancelled").checked=!!e.cancelled;$("copy").style.display="block";$("del").style.display="block";M.classList.add("open");S.style.transform="translateY(0)";requestAnimationFrame(()=>$("name").focus())}
function add(){edit=null;$("badge").textContent="NOVÁ HODINA";$("mt").textContent="Pridať hodinu";["name","format","room","teacher","date","note"].forEach(id=>$(id).value="");$("day").value=0;$("start").value="08:00";$("end").value="08:55";$("color").value=DEFAULT_COLOR;$("cancelled").checked=false;$("copy").style.display="none";$("del").style.display="none";M.classList.add("open");S.style.transform="translateY(0)";requestAnimationFrame(()=>$("name").focus())}
function close(){M.classList.remove("open");S.style.transform="translateY(0)"}
$("add").onclick=add;$("cancel").onclick=close;$("save").onclick=()=>{const d={day:+$("day").value,start:$("start").value,end:$("end").value,name:$("name").value.trim()||"Nová hodina",type:"mine",format:$("format").value.trim(),room:$("room").value.trim(),teacher:$("teacher").value.trim(),date:$("date").value.trim(),note:$("note").value.trim(),color:$("color").value||DEFAULT_COLOR,cancelled:$("cancelled").checked};if(mm(d.end)<=mm(d.start))return;if(edit){const i=E.findIndex(x=>x.id===edit);if(i>=0)E[i]={...E[i],...d}}else E.push({...d,id:crypto.randomUUID?.()||String(Date.now())});save();close();render()};$("copy").onclick=()=>{if(!edit)return;const e=E.find(x=>x.id===edit);if(!e)return;E.push({...e,id:crypto.randomUUID?.()||String(Date.now())});save();close();render()};$("del").onclick=()=>{if(!edit)return close();E=E.filter(x=>x.id!==edit);save();close();render()};
function sheetDrag(hit,target,fn){let s=null;hit.onpointerdown=e=>{e.preventDefault();s=e.clientY;try{hit.setPointerCapture(e.pointerId)}catch{};target.classList.add("drag")};hit.onpointermove=e=>{if(s===null)return;e.preventDefault();target.style.transform=`translateY(${Math.min(360,Math.max(0,e.clientY-s))}px)`};hit.onpointerup=e=>{if(s===null)return;const d=Math.max(0,e.clientY-s);s=null;target.classList.remove("drag");if(d>55){target.style.transform="translateY(110%)";setTimeout(fn,180)}else target.style.transform="translateY(0)"}};sheetDrag($("grab"),S,close);sheetDrag($("tgrab"),TS,()=>TM.classList.remove("open"));$("title").onclick=()=>{$("titleInput").value=localStorage.getItem(TK)||"POLM · ZS 2026/27";TM.classList.add("open")};$("tcancel").onclick=()=>TM.classList.remove("open");$("tsave").onclick=()=>{localStorage.setItem(TK,$("titleInput").value.trim()||"POLM · ZS 2026/27");TM.classList.remove("open");render()};document.addEventListener("dblclick",e=>e.preventDefault(),{passive:false});document.addEventListener("gesturestart",e=>e.preventDefault(),{passive:false});fill();render();