document.body.innerHTML=`<div class="app"><header class="top"><div class="brand"><i class="dot"></i><div class="title" id="title">POLM · ZS 2026/27</div></div><div class="topActions"><button class="zoomBtn" id="zoomOut" aria-label="Oddialiť">−</button><button class="zoomBtn zoomVal" id="zoomVal" aria-label="Mierka">100%</button><button class="zoomBtn" id="zoomIn" aria-label="Priblížiť">+</button><button class="zoomBtn fitBtn" id="zoomFit" aria-label="Celý rozvrh">FIT</button><button class="add" id="add" aria-label="Pridať">＋</button></div></header><main class="board" id="board"><div class="scaleWrap" id="scaleWrap"><div class="grid" id="grid"></div></div></main></div><div class="modal" id="modal"><section class="sheet" id="sheet"><div class="grabhit" id="grab"><i class="grab"></i></div><div class="badge" id="badge">NOVÁ HODINA</div><h2 id="mt">Pridať hodinu</h2><div class="form"><div class="field full"><label>Predmet</label><input id="name" autocomplete="off"></div><div class="field"><label>Deň</label><select id="day"><option value="0">Pondelok</option><option value="1">Utorok</option><option value="2">Streda</option><option value="3">Štvrtok</option><option value="4">Piatok</option></select></div><div class="field"><label>Začiatok</label><select id="start"></select></div><div class="field"><label>Koniec</label><select id="end"></select></div><div class="field"><label>P/S</label><input id="format"></div><div class="field"><label>Miestnosť</label><input id="room"></div><div class="field full"><label>Vyučujúci</label><input id="teacher"></div><div class="field"><label>Dátumy</label><input id="date"></div><div class="field"><label>Farba</label><input id="color" type="color" value="#3e88b4" class="colorInput"></div><div class="field full"><label>Moja poznámka</label><textarea id="note"></textarea></div><div class="field full"><label>Osobné označenie</label><label class="check"><input type="checkbox" id="cancelled"> Túto hodinu tento týždeň nemám</label></div></div><div class="actions"><button class="cancel" id="cancel">Zrušiť</button><button class="copy" id="copy">Kopírovať</button><button class="delete" id="del">Vymazať</button><button class="save" id="save">Uložiť</button></div></section></div><div class="modal titleModal" id="tm"><section class="sheet" id="ts"><div class="grabhit" id="tgrab"><i class="grab"></i></div><div class="badge">NASTAVENIE</div><h2>Názov rozvrhu</h2><div class="form"><div class="field full"><label>Názov</label><input id="titleInput" autocomplete="off"></div></div><div class="actions"><button class="cancel" id="tcancel">Zrušiť</button><button class="save" id="tsave">Uložiť</button></div></section></div>`;
const $=id=>document.getElementById(id),G=$("grid"),W=$("scaleWrap"),B=$("board"),M=$("modal"),S=$("sheet"),TM=$("tm"),TS=$("ts");
const TIMES=T.filter(x=>mm(x)<=mm("19:55")),DEFAULT_COLOR="#3e88b4",MIN_SCALE=.25,MAX_SCALE=1.35;
let E=load(),edit=null,gesture=null,press=null,pinch=null,viewScale=1,baseW=0,baseH=0;
function mm(t){let[a,b]=t.split(":").map(Number);return a*60+b}function ff(v){v=Math.round(v);return String(Math.floor(v/60)).padStart(2,"0")+":"+String(v%60).padStart(2,"0")}
function esc(s){return String(s??"").replace(/[&<>\\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\\":"&#92;","\"":"&quot;"}[c]))}
function clean(s){return String(s||"").replace(/\s*\(profilový predmet\)/gi,"").replace(/\s*\(PP\)/gi,"").trim()}
function load(){try{let x=JSON.parse(localStorage.getItem(K));if(Array.isArray(x)&&x.length)return x.map((e,i)=>({...e,id:e.id||"e"+i,cancelled:!!e.cancelled,color:e.color||DEFAULT_COLOR}))}catch{}return raw.map((e,i)=>({...e,id:"s"+i,cancelled:false,color:e.color||DEFAULT_COLOR}))}
function save(){localStorage.setItem(K,JSON.stringify(E))}
function metrics(){const mobile=innerWidth<=700;return{day:mobile?166:300,time:mobile?60:96,ppm:mobile?2.2:1.65,head:mobile?44:50}}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function snapStart(v){let best=TIMES[0],dist=1e9;for(const t of TIMES){const d=Math.abs(mm(t)-v);if(d<dist){dist=d;best=t}}return best}
function snapEnd(v,start){const s=mm(start);let best=TIMES[TIMES.length-1],dist=1e9;for(const t of TIMES){const n=mm(t);if(n<=s)continue;const d=Math.abs(n-v);if(d<dist){dist=d;best=t}}return best}
function eventHeight(e,m){const si=Math.max(0,TIMES.findIndex(t=>t===e.start)),next=TIMES[Math.min(TIMES.length-1,si+1)],minDur=Math.max(45,mm(next)-mm(e.start));return Math.max(minDur*m.ppm-8,(mm(e.end)-mm(e.start))*m.ppm-8)}
function rect(e,m){return{x:m.time+clamp(+e.day,0,D.length-1)*m.day+4,y:m.head+(mm(e.start)-mm(TIMES[0]))*m.ppm+4,w:m.day-8,h:eventHeight(e,m)}}
function gridHeight(m){return m.head+(mm("19:10")-mm(TIMES[0]))*m.ppm}
function conflicts(){const bad=new Set;for(let i=0;i<E.length;i++)for(let j=i+1;j<E.length;j++){const a=E[i],b=E[j];if(a.day===b.day&&mm(a.start)<mm(b.end)&&mm(a.end)>mm(b.start)){bad.add(a.id);bad.add(b.id)}}return bad}
function fitText(el){const box=el.querySelector(".content"),name=el.querySelector(".name"),teacher=el.querySelector(".teacher"),info=el.querySelector(".info");if(!box||!name)return;let ns=parseFloat(getComputedStyle(name).fontSize),ts=teacher?parseFloat(getComputedStyle(teacher).fontSize):0,is=info?parseFloat(getComputedStyle(info).fontSize):0;for(let i=0;i<36&&box.scrollHeight>box.clientHeight+1;i++){if(name&&ns>8.2){ns-=.25;name.style.fontSize=ns+"px"}if(teacher&&ts>6.1){ts-=.15;teacher.style.fontSize=ts+"px"}if(info&&is>5.1){is-=.1;info.style.fontSize=is+"px"}}}
function render(){const m=metrics();baseW=m.time+m.day*D.length;baseH=gridHeight(m);G.innerHTML="";G.style.width=baseW+"px";G.style.minWidth=baseW+"px";G.style.height=baseH+"px";G.style.minHeight=baseH+"px";const corner=document.createElement("div");corner.className="corner";corner.style.width=m.time+"px";corner.style.height=m.head+"px";corner.textContent="ČAS / DEŇ";G.appendChild(corner);TIMES.slice(0,-1).forEach((t,i)=>{const q=document.createElement("div");q.className="time";q.style.top=m.head+(mm(t)-mm(TIMES[0]))*m.ppm+"px";q.style.width=m.time+"px";q.style.height=(mm(TIMES[i+1])-mm(t))*m.ppm+"px";q.textContent=t;G.appendChild(q)});D.forEach((d,di)=>{const q=document.createElement("div");q.className="day";q.style.left=m.time+di*m.day+"px";q.style.width=m.day+"px";q.style.height=m.head+"px";q.textContent=d;G.appendChild(q);for(let i=0;i<TIMES.length-2;i++){const c=document.createElement("div");c.className="cell"+(i%2?" alt":"");c.style.left=m.time+di*m.day+"px";c.style.top=m.head+(mm(TIMES[i])-mm(TIMES[0]))*m.ppm+"px";c.style.width=m.day+"px";c.style.height=(mm(TIMES[i+1])-mm(TIMES[i]))*m.ppm+"px";G.appendChild(c)}});const bad=conflicts();E.forEach(e=>draw(e,bad,m));applyScale(viewScale)}
function draw(e,bad,m){const r=rect(e,m),el=document.createElement("div");el.className="event mine"+(bad.has(e.id)?" conflict":"")+(e.cancelled?" cancelled":"");el.dataset.id=e.id;el.style.left=r.x+"px";el.style.top=r.y+"px";el.style.width=r.w+"px";el.style.height=r.h+"px";el.style.background=e.color||DEFAULT_COLOR;const n=clean(e.name),long=n.length>42;el.classList.toggle("compact",r.h<130);const details=[e.format,e.room,e.date].filter(Boolean).join(" · ");el.innerHTML=`<div class="content"><div class="name ${long?"long":""}">${esc(n)}</div>${e.teacher?`<div class="teacher">${esc(e.teacher)}</div>`:""}${details?`<div class="info">${esc(details)}</div>`:""}</div>${e.cancelled?'<div class="cancelLabel">×</div>':""}${bad.has(e.id)?'<div class="conflictBadge">KOLÍZIA</div>':""}<div class="handle hy" data-h="y"><i></i></div>`;G.appendChild(el);requestAnimationFrame(()=>fitText(el));el.addEventListener("pointerdown",ev=>down(ev,e,el),{passive:false})}
function clearPress(){if(press){clearTimeout(press.timer);try{press.el.releasePointerCapture?.(press.pointerId)}catch{};press=null}}
function cancelGesture(){if(gesture){gesture.el.classList.remove("dragging","resizing");gesture.el.style.touchAction="none";try{gesture.el.releasePointerCapture?.(gesture.pointerId)}catch{};gesture=null}}
function beginMove(ev,e,el){if(!press||press.pointerId!==ev.pointerId)return;press.active=true;gesture={kind:"move",id:e.id,el,pointerId:ev.pointerId,sx:ev.clientX,sy:ev.clientY,orig:{day:e.day,start:e.start,end:e.end,left:parseFloat(el.style.left)||0,top:parseFloat(el.style.top)||0},m:metrics(),moved:false};el.classList.add("dragging");el.style.touchAction="none"}
function down(ev,e,el){if(ev.pointerType!=="touch"&&ev.button!==undefined&&ev.button!==0)return;if(pinchevent(ev))return;ev.preventDefault();ev.stopPropagation();const h=ev.target.closest?.(".handle")?.dataset.h;if(h){clearPress();cancelGesture();const m=metrics();gesture={kind:"resizeY",id:e.id,el,pointerId:ev.pointerId,sx:ev.clientX,sy:ev.clientY,orig:{start:e.start,end:e.end,height:parseFloat(el.style.height)||eventHeight(e,m)},moved:false,m};el.classList.add("resizing");el.style.touchAction="none";try{el.setPointerCapture(ev.pointerId)}catch{};return}clearPress();press={id:e.id,el,pointerId:ev.pointerId,x:ev.clientX,y:ev.clientY,active:false,moved:false,timer:setTimeout(()=>beginMove({clientX:press?.x,clientY:press?.y,pointerId:ev.pointerId},e,el),280)};try{el.setPointerCapture(ev.pointerId)}catch{}}
function pinchevent(ev){return !!pinch&&ev.pointerType==="touch"}
function move(ev){if(pinchevent(ev))return;if(press&&press.pointerId===ev.pointerId&&!press.active){if(Math.hypot(ev.clientX-press.x,ev.clientY-press.y)>10){press.moved=true;clearTimeout(press.timer);press.timer=null}return}if(!gesture||gesture.pointerId!==ev.pointerId)return;const e=E.find(x=>x.id===gesture.id);if(!e)return;ev.preventDefault();ev.stopPropagation();const m=gesture.m;if(gesture.kind==="move"){const s=viewScale||1,dx=(ev.clientX-gesture.sx)/s,dy=(ev.clientY-gesture.sy)/s,h=eventHeight(e,m),left=clamp(gesture.orig.left+dx,m.time+4,m.time+4+(D.length-1)*m.day),top=clamp(gesture.orig.top+dy,m.head+4,Math.max(m.head+4,gridHeight(m)-h-4));gesture.live={x:left,y:top};gesture.el.style.left=left+"px";gesture.el.style.top=top+"px"}else{const startMin=mm(gesture.orig.start),next=TIMES[Math.min(TIMES.length-1,Math.max(1,TIMES.indexOf(gesture.orig.start)+1))],minH=Math.max(54,(mm(next)-startMin)*m.ppm-8),bottomStart=m.head+(startMin-mm(TIMES[0]))*m.ppm+4,maxH=Math.max(minH,gridHeight(m)-bottomStart-2);gesture.live={height:clamp(gesture.orig.height+(ev.clientY-gesture.sy),minH,maxH)};gesture.el.style.height=gesture.live.height+"px"}gesture.moved=true}
document.addEventListener("pointermove",move,{passive:false});document.addEventListener("pointerup",finishPointer,true);document.addEventListener("pointercancel",cancelPointer,true);
function finishPointer(ev){if(gesture&&gesture.pointerId===ev.pointerId){const g=gesture,e=E.find(x=>x.id===g.id);g.el.releasePointerCapture?.(ev.pointerId);g.el.classList.remove("dragging","resizing");g.el.style.touchAction="none";if(e&&g.moved){if(g.kind==="move"){const m=g.m,dx=g.live.x-g.orig.left,dy=g.live.y-g.orig.top;e.day=clamp(g.orig.day+Math.round(dx/m.day),0,D.length-1);const rawStart=mm(g.orig.start)+dy/m.ppm;e.start=snapStart(clamp(rawStart,mm(TIMES[0]),mm(TIMES[TIMES.length-1])-1));const dur=Math.max(1,mm(g.orig.end)-mm(g.orig.start)),wanted=mm(e.start)+dur;e.end=TIMES.some(t=>mm(t)===wanted)?ff(wanted):snapEnd(wanted,e.start);if(mm(e.end)>mm(TIMES[TIMES.length-1]))e.end=TIMES[TIMES.length-1]}else{const endMin=mm(g.orig.start)+(g.live.height+8)/g.m.ppm;e.end=snapEnd(Math.min(endMin,mm(TIMES[TIMES.length-1])),g.orig.start)}save();render()}gesture=null;return}if(press&&press.pointerId===ev.pointerId){const p=press,e=E.find(x=>x.id===p.id),wasActive=p.active,wasMoved=p.moved;clearPress();if(!wasActive&&!wasMoved&&e)open(e)}}
function cancelPointer(ev){if(press&&press.pointerId===ev.pointerId)clearPress();if(gesture&&gesture.pointerId===ev.pointerId)cancelGesture()}
function fill(){$("start").innerHTML=TIMES.slice(0,-1).map(t=>`<option>${t}</option>`).join("");$("end").innerHTML=TIMES.slice(1).map(t=>`<option>${t}</option>`).join("")}
function open(e){if(!e)return;edit=e.id;$("badge").textContent="UPRAVIŤ HODINU";$("mt").textContent="Upraviť hodinu";$("name").value=e.name||"";$("day").value=e.day;$("start").value=e.start;$("end").value=e.end;$("format").value=e.format||"";$("room").value=e.room||"";$("teacher").value=e.teacher||"";$("date").value=e.date||"";$("note").value=e.note||"";$("color").value=e.color||DEFAULT_COLOR;$("cancelled").checked=!!e.cancelled;$("copy").style.display="block";$("del").style.display="block";M.classList.add("open");S.style.transform="translateY(0)";requestAnimationFrame(()=>$("name").focus())}
function add(){edit=null;$("badge").textContent="NOVÁ HODINA";$("mt").textContent="Pridať hodinu";["name","format","room","teacher","date","note"].forEach(id=>$(id).value="");$("day").value="0";$("start").value=TIMES[0];$("end").value=TIMES[1];$("color").value=DEFAULT_COLOR;$("cancelled").checked=false;$("copy").style.display="none";$("del").style.display="none";M.classList.add("open");S.style.transform="translateY(0)";requestAnimationFrame(()=>$("name").focus())}
function close(){M.classList.remove("open");edit=null}
$("add").onclick=add;$("cancel").onclick=close;$("save").onclick=()=>{const x={id:edit||("m"+Date.now()),day:+$("day").value,start:$("start").value,end:$("end").value,name:$("name").value.trim(),format:$("format").value.trim(),room:$("room").value.trim(),teacher:$("teacher").value.trim(),date:$("date").value.trim(),note:$("note").value.trim(),color:$("color").value,cancelled:$("cancelled").checked};if(!x.name)return;const i=E.findIndex(e=>e.id===edit);if(i>=0)E[i]=x;else E.push(x);save();close();render()};$("del").onclick=()=>{if(edit!=null){E=E.filter(e=>e.id!==edit);save();close();render()}};$("copy").onclick=()=>{if(edit==null)return;const e=E.find(x=>x.id===edit);if(!e)return;const c={...e,id:"m"+Date.now()};E.push(c);save();close();render();open(c)};$("tcancel").onclick=()=>TM.classList.remove("open");$("tsave").onclick=()=>{const v=$("titleInput").value.trim()||"POLM · ZS 2026/27";$("title").textContent=v;localStorage.setItem(TK,v);TM.classList.remove("open")};
let modalDrag=null;function setupSheetDrag(hit,sheet,modal){hit.addEventListener("pointerdown",ev=>{if(ev.pointerType!=="touch")return;ev.preventDefault();sheet.classList.add("drag");modalDrag={hit,sheet,modal,pid:ev.pointerId,y:ev.clientY};try{hit.setPointerCapture(ev.pointerId)}catch{}});hit.addEventListener("pointermove",ev=>{if(!modalDrag||modalDrag.pid!==ev.pointerId)return;const dy=Math.max(0,ev.clientY-modalDrag.y);sheet.style.transform=`translateY(${dy}px)`});hit.addEventListener("pointerup",ev=>{if(!modalDrag||modalDrag.pid!==ev.pointerId)return;const dy=Math.max(0,ev.clientY-modalDrag.y);sheet.classList.remove("drag");if(dy>120)modal.classList.remove("open");sheet.style.transform="translateY(0)";modalDrag=null});hit.addEventListener("pointercancel",()=>{if(modalDrag){sheet.classList.remove("drag");sheet.style.transform="translateY(0)";modalDrag=null}})}
fill();render();window.addEventListener("resize",()=>{const old=baseW;render();if(!old||old!==baseW)fit()});setTimeout(()=>fit(),80);